name: youplay_music
description: "you play music"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # core
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.0
  url_launcher: ^6.2.6
  path_provider: ^2.1.0
  crypto: ^3.0.3

  # audio libs
  on_audio_query: ^2.9.0
  just_audio: ^0.9.42
  audio_session: ^0.1.7
  audio_service: ^0.18.15
  just_audio_background: ^0.0.1-beta.17

  # permissions & sharing
  permission_handler: ^11.3.1
  share_plus: ^10.1.1
  headset_connection_event: ^4.0.2
  ringtone_set_plus: ^0.0.2+2

  # optional older player lib
  audioplayers: ^6.1.0

  # ðŸŒŽ LOCALIZATION packages
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.0

  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
    # ðŸŒŽ language JSON folder
    - assets/lang/
